/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alec.Tunbridge' at '27/08/15 08:50' with Gradle 1.10
 *
 * @author Alec.Tunbridge, @date 27/08/15 08:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
